example/lib/main.dart, lib/photo_view.dart, lib/photo_view_image_wrapper.dart
=> Add gif support

lib/photo_view.dart, lib/photo_view_gallery.dart
=> Fix default value for gaplessplayback in PhotoViewInline's constructor

lib/photo_view_gallery.dart
I want to handle scale change event even in gallery mode.
Thank you very much for your great work!
=> Added scaleStateChangedCallback property to PhotoViewGallery

lib/photo_view_gallery.dart
=> add defalut page index to PhotoViewGallery

pubspec.lock, pubspec.yaml
=> dependencies

example/lib/screens/examples/gallery_example.dart, lib/photo_view.dart, lib/photo_view_gallery.dart, lib/src/photo_view_image_wrapper.dart
=> physics & format

lib/photo_view_gallery.dart
Adding support for initialScale, minScale and maxScale in Gallery view
=> Issue #104

example/lib/screens/examples/gallery/gallery_example.dart, example/lib/screens/examples/gallery/gallery_example_item.dart, example/lib/screens/home_screen.dart, lib/photo_view_gallery.dart, lib/src/photo_view_controller.dart, pubspec.lock
Add builder pattern.
REF: #78 #113
=> gallery builder

lib/photo_view.dart, lib/src/photo_view_image_wrapper.dart
Solving the problem of determining the position of clicking on the image (#49)
=> Added onTapUp & onTapDown callbacks

example/lib/screens/examples/controller_example.dart, example/lib/screens/examples/gallery/gallery_example.dart, lib/photo_view.dart, lib/photo_view_gallery.dart, lib/src/photo_view_controller.dart, lib/src/photo_view_controller_delegate.dart, lib/src/photo_view_image_wrapper.dart, lib/src/photo_view_utils.dart, test/controller_test.dart, test/scale_state_controller_test.dart
=> Scalestate controller

example/lib/screens/examples/gallery/gallery_example.dart, example/lib/screens/examples/gallery/gallery_example_item.dart, lib/photo_view_gallery.dart
=> Gallery custom child

lib/src/photo_view_utils.dart, pubspec.lock, pubspec.yaml
Due to the conversation on #135, this PR aims to keep PhotoView compatible with the Flutter's stable channel.
=> Flutter error compat

lib/src/photo_view_image_wrapper.dart
=> ontapup & ontapdown

lib/photo_view_gallery.dart
Implements the PageView reverse parameter, saves having to reverse the given data.
=> Add the PageView reverse parameter

lib/photo_view.dart
=> Fix comment's spelling

lib/photo_view_gallery.dart
by adding scaleStateCycle parameter to PhotoViewGalleryPageOptions , photo  gallery can custom scaleStateCycle .
=> add scaleStateCycle parameter in PhotoViewGalleryPageOptions

lib/src/photo_view_image_wrapper.dart
See https://github.com/renancaraujo/photo_view/issues/134
=> Correct overriding gesture handlers

example/.gitignore, example/android/app/build.gradle, example/android/build.gradle, example/android/gradle.properties, example/android/gradle/wrapper/gradle-wrapper.properties, example/lib/screens/examples/controller_example.dart, example/lib/screens/examples/gallery/gallery_example.dart, lib/photo_view.dart, lib/photo_view_gallery.dart, lib/src/controller/photo_view_controller.dart, lib/src/controller/photo_view_controller_delegate.dart, lib/src/photo_view_image_wrapper.dart
Update example app deps, fix typos and fixes #174 .
=> Update deps, fix typos, fix issues

example/lib/screens/examples/gallery/gallery_example.dart, lib/photo_view.dart, lib/photo_view_gallery.dart, lib/src/controller/photo_view_controller_delegate.dart, lib/src/photo_view_image_wrapper.dart, lib/src/photo_view_pageview_wrapper.dart
After rebase with master, I open this new pull request, please take a look, thank you!
=> Let user scroll to next page when PageView child is zooming (#41)

example/web/index.html
See #200 
to run
```cmd
photo_view ❯❯❯ cd example
photo_view/example ❯❯❯ flutter run -d chrome
```
=> Add file for run on the web in example directory

lib/src/controller/photo_view_controller_delegate.dart
=> Clamp position on every scale update

example/lib/screens/examples/custom_child_examples.dart, lib/photo_view.dart
=> Custom child size now is optional.

example/lib/screens/examples/dialog_example.dart, example/lib/screens/examples/full_screen_examples.dart, example/lib/screens/examples/hero_example.dart, example/lib/screens/home_screen.dart, lib/photo_view.dart, lib/photo_view_gallery.dart, lib/src/core/photo_view_core.dart, lib/src/core/photo_view_gesture_detector.dart, lib/src/core/photo_view_hit_corners.dart
=> Add tightmode, expose gesture detector scope, minor fix corner hit test and add one tap example

lib/photo_view_gallery.dart
Made childSize optional for PhotoViewGalleryPageOptions.customChild.
=> custom child size (PhotoViewGalleryPageOptions)

lib/photo_view.dart, lib/photo_view_gallery.dart
add loadFailedChild when the image failed to load
=> Add loadFailedChild

README.md, example/lib/screens/examples/full_screen_examples.dart, example/lib/screens/examples/gallery/gallery_example.dart, example/lib/screens/examples/hero_example.dart, lib/photo_view.dart, lib/photo_view_gallery.dart
use the provider onChunk event to be able to have progress bar that show the actual progress of loading the Image
=> Deprecate loadChild and add loadBuilder that has load progress information

example/lib/main.dart, example/lib/screens/examples/full_screen_examples.dart, lib/photo_view_gallery.dart, lib/src/core/photo_view_core.dart
=> Fix base position

example/lib/screens/examples/controller_example.dart, lib/src/controller/photo_view_controller_delegate.dart, lib/src/core/photo_view_core.dart, lib/src/photo_view_scale_state.dart
Avoid extra scale state controller value streamed, as poinetd on #227
=> Avoid extra controller stream value

lib/photo_view.dart, lib/photo_view_gallery.dart
Remove deprecated API for next release.
=> Remove loading child

example/lib/screens/examples/gallery/gallery_example.dart, lib/src/core/photo_view_gesture_detector.dart, lib/src/core/photo_view_hit_corners.dart
This should fix the following issues:
#293 
#271
=> Fix double and single tap on gallery

README.md
Hi
Thanks for this library, I found a class in the readme that does not exist.
Should it be `PhotoViewHeroAttributes`?
=> Fix hero attributes class on README

.github/no-response.yml, example/lib/screens/examples/controller_example.dart, example/pubspec.lock, lib/photo_view.dart, lib/src/controller/photo_view_controller.dart, lib/src/controller/photo_view_controller_delegate.dart, lib/src/core/photo_view_core.dart, lib/src/utils/photo_view_utils.dart
=> Starting scale on controller

lib/src/photo_view_wrappers.dart
This may fix #341
Added recycling mechanics for the internal image stream.
=> Fix image provider lifecycle

lib/src/core/photo_view_core.dart
=> Fix(#399) null check

example/pubspec.lock, lib/src/core/photo_view_core.dart, lib/src/core/photo_view_gesture_detector.dart
This addresses #441 without breaking for stable channel users.
=> Fix(#441) add allowed pointer

lib/photo_view_gallery.dart
Add allowImplicitScrolling for preloading next page on PageView.
=> Add allowImplicitScrolling for preloading next page on PageView

analysis_options.yaml, example/pubspec.lock, lib/src/core/photo_view_core.dart, lib/src/photo_view_wrappers.dart
=> Fix(#464) network image

README.md
Hey there, 
I just fixed the broken example URL and update some others URLs to avoid redirects on old repos
Thanks for your awesome work!
=> Update README Urls

README.md
=> doc: Fix github build badge
