bluefireteam/photo_view

- lib/photo_view.dart
- lib/photo_view_image_wrapper.dart
Hi!
The black background colour didn't exactly fit my app, so I made a tiny modification so that the widget now accepts a backgroundColor property.
If there's no colour specified, it defaults to the previous black colour.
Thanks for your work on the plugin!
> Added backgroundColor property

- example/lib/main.dart
- lib/photo_view.dart
- lib/photo_view_image_wrapper.dart
- lib/photo_view_scale_boundaries.dart
- lib/photo_view_scale_boundary.dart
- lib/photo_view_scale_state.dart
- lib/photo_view_utils.dart
- test/photo_view_utils_test.dart
As asked by @sgon00, this PR adds the possibility of applying the states "covered" and "contained" as ´minScale´ or ´maxScale´.
```dart
new PhotoView(
imageProvider: imageProvider,
loadingChild: new LoadingText(),
backgroundColor: Colors.white,
minScale: PhotoViewScaleBoundary.contained,
maxScale: PhotoViewScaleBoundary.covered
);
```
> Boundary constants

- pubspec.yaml
noticed that my `pubspec.lock` was injected with `csslib` `html` _packages_ and narrowed it down to your package. 
im not entirely sure how package `dependencies` and `dev_dependencies` relate to each other with dart and pub or how transitive dependencies get added. but i believe its best practice to only add direct dependencies to each package and what is used for `test` and `build script` as _dev_dependencies_.
> move test package to dev_dependencies

- lib/photo_view_gallery.dart
Reverts renancaraujo/photo_view#72
Unnecessary option, the desired effect can be achieved by specifying a `PageController` to `PhotoViewGallery`.
It is bugging the gallery example.
> Revert "add defalut page index to PhotoViewGallery"

- lib/photo_view.dart
The value set for `transitionOnUserGestures` was not passed to `PhotoViewImageWrapper`. This cause it to be always the default value of `false` regardless.
> FIX: transitionOnUserGestures value not used 

- example/lib/screens/examples/controller_example.dart
- lib/photo_view.dart
- lib/photo_view_gallery.dart
- lib/src/photo_view_controller.dart
- lib/src/photo_view_image_wrapper.dart
- lib/src/photo_view_scale_state.dart
- lib/src/photo_view_utils.dart
- test/controller_test.dart
GREAT REPO! 👍 
I have added two more scaleStates: '**zoomedIn**' and '**zoomedOut**'.
The trigger between those two states is currently the **initialScale**:
_zoomedOut **<=** initialScale **<** zoomedIn_
_zoomedOut_ -> **unlocks** the image
_zoomedIn_ -> **locks** the image
The (default)StateCycle stays the same.
**However, the scaleState 'zooming' becomes unnecessary.**
I've encountered some performance issues, so I've implemented a new stream that will fire **ONLY** if a scaleState change is detected.
At this point, the additional customization of the trigger point will be EASY :)
i guess this will fix #105 
and is at least an approach for #41
> UNLOCK image if image is zoomedOut

- lib/src/photo_view_utils.dart
- pubspec.lock
- pubspec.yaml
Flutter `1.5.9-pre.94` on the master channel introduced  breaking changes in `FlutterError`, `FlutterErrorDetails` and `InformationCollector` (flutter/flutter#30983) which broke `photo_view` and a lot of other packages (flutter/flutter#31962). This commit fixes the issue for `photo_view`.
Fixes #135
> Fix FlutterError breaking changes

- lib/photo_view.dart
> Fix for Flutter 1.6.3

- README.md
- example/lib/screens/examples/gallery/gallery_example.dart
- example/lib/screens/examples/hero_example.dart
- lib/photo_view.dart
- lib/photo_view_gallery.dart
- lib/src/hero_attributes.dart
- lib/src/photo_view_controller.dart
- lib/src/photo_view_controller_delegate.dart
- lib/src/photo_view_image_wrapper.dart
- lib/src/photo_view_typedefs.dart
- lib/src/photo_view_utils.dart
- pubspec.lock
- test/scale_state_controller_test.dart
> Implement `HeroProperties`

- lib/src/controller/photo_view_controller_delegate.dart
- lib/src/core/photo_view_core.dart
- lib/src/photo_view_scale_state.dart
- lib/src/utils/photo_view_utils.dart
Ref: #163
In this PR:
We cache the rendered `ScaleBoundary` into the core's state. If we build a different one, we mark the delegate to recalc the scale from the `scaleState` only if the user is not zooming (in or out).
> Add recalc scale behavior

- lib/src/core/photo_view_gesture_detector.dart
Avoiding context.inheritFromWidgetOfExactType and using context.dependOnInheritedWidgetOfExactType
> Updating usage of InheritedWidget due to Flutter SDK v1.12.1 

- example/lib/screens/examples/full_screen_examples.dart
- lib/photo_view.dart
- lib/photo_view_gallery.dart
- lib/src/core/photo_view_core.dart
```dart
@override
Widget build(BuildContext context) {
return Container(
child: PhotoView(
imageProvider: AssetImage("assets/large-image.jpg"),
filterQuality: FilterQuality.medium,
)
);
}
```
> Add filterQuality property to improve image quality after scale

- lib/src/core/photo_view_gesture_detector.dart
Straight up mark gesture as won when a gesture scope is detected, instead f calli9ng resolve, which interferes on ScaleGestureRecognizer's lifecycle. 
Supposedly should fix #212 and correlates.
> Fix(#212) GestureDetector winning arena

- example/lib/screens/examples/rotation_examples.dart
- example/lib/screens/home_screen.dart
- lib/src/controller/photo_view_controller.dart
- lib/src/core/photo_view_core.dart
**Originally #259**
Allows the photo view to be rotated by setting the PhotoViewController.rotation property even when the photo view's enableRotation property is not enabled.
Relates to issue #257.
> Allow programmatic rotate when PhotoView enableRotation is disabled

- example/lib/screens/common/app_bar.dart
- example/lib/screens/common/common_example_wrapper.dart
- example/lib/screens/examples/network-images.dart
- example/lib/screens/examples/rotation_examples.dart
- lib/photo_view.dart
- lib/photo_view_gallery.dart
- lib/src/core/photo_view_hit_corners.dart
- lib/src/photo_view_default_widgets.dart
- lib/src/photo_view_wrappers.dart
This PR fixes some issues regarding error builder.
- fix #337. 
- Remove deprecated `loadingChild`
- Makes `backgroundDecoration` to be the background of the default error icon.
> Fix error builder to be (ever) called; Remove deprecated loading child

- lib/photo_view.dart
- lib/photo_view_gallery.dart
- lib/src/core/photo_view_core.dart
- lib/src/photo_view_wrappers.dart
Gallery could not move caused by onScaleEnd is non-nullable.
onScaleEnd now is non-nullable unlike onTapUp/onTapDown.
I think onScaleEnd should be nullable like onTapUp/onTapDown.
So I added null operator to onScaleEnd.
And change @ required to required like #375 .
After fixed it, Gallery could move.
> Fix onScaleEnd operator

- lib/src/core/photo_view_gesture_detector.dart
Because of the change in https://github.com/flutter/flutter/commit/3b19dfd4da378fc6333f56d034c7eb1312896a6c, it compiles incorrectly and does not run.
> Migration to master api.

- lib/photo_view.dart
For now, PhotoView in gallery will reset state when scrolling to another page. The fix is for keepling scale state.
> keep PhotoView state

- lib/src/core/photo_view_core.dart
With the new stable version `2.10.0` of Flutter, there is a new problem.
When building this widget with some images, it works fine.
But when leaving/disposing this widget, there is crash report in the console that says `Looking up a deactivated widget's ancestor is unsafe`.
The solution for this problem was to initialize the controller inside `initState` to ensure, that everything was initialized correctly in the lifecycle of a stateful widget.
When the widget is disposed, there is no problem disposing these controllers.
> Flutter Update: 2.10.0 - Fix: Looking up a deactivated widget's ancestor is unsafe fix

- lib/photo_view.dart
- lib/photo_view_gallery.dart
This introduces a `wantKeepAlive` parameter to make the feature (_keep PhotoView state #452_, which keeps an image scale state) optional.
Comparing it with the iOS Photo app, I suggest the default value to be `false` :)
closes #478
> added `wantKeepAlive` parameter to make it optional

- lib/photo_view.dart
- lib/photo_view_gallery.dart
- lib/src/core/photo_view_core.dart
- lib/src/photo_view_wrappers.dart
Pass through [`semanticLabel`](https://api.flutter.dev/flutter/widgets/Image/semanticLabel.html) for [screen readers](https://docs.flutter.dev/development/accessibility-and-localization/accessibility).
> Pass through semanticLabel

- lib/src/core/photo_view_gesture_detector.dart
According to GestureDector.dragStartBehavior description between DragStartBehavior.start and DragStartBehavior.down, to make image scalable more smoothly, we should set PhotoViewGestureRecognizer dragStartBehavior to DragStartBehavior.start.
> make scale more smoothly

- lib/photo_view.dart
- lib/src/core/photo_view_core.dart
- lib/src/photo_view_wrappers.dart
Actual behavior : 
User can scale image in or out. When user release scale gesture, app will rescale if current user scale choice is behind defined limit (maxScale and minScale).
Proposition : 
A new property to prevent the user to scale behind theses limit.
> feature/strictscale: add possibility to restrict user scale, fix issue #85

- lib/photo_view_gallery.dart
Adds the pageSnapping option to give the dev the option to view continually the image from the gallery, without snapping every time.
The main reason for me doing this addition is to add this option also on the [pdfx](https://pub.dev/packages/pdfx) package, it is useful for the web apps with vertical viewing.
> Added pageSnapping option

- lib/photo_view.dart
- lib/src/utils/photo_view_utils.dart
The Dart analyzer will soon be changed so that if the `default` clause of a `switch` statement is determined to be unreachable by the exhaustiveness checker, a new warning of type
`unreachable_switch_default` will be issued. This parallels the behavior of the existing `unreachable_switch_case` warning, which is issued whenever a `case` clause of a `switch` statement is determined to be unreachable. For details see
https://github.com/dart-lang/sdk/issues/54575.
This PR deletes unreachable `default` clauses from `photo_view` now, to avoid a spurious warning when the analyzer change lands.
> Delete unreachable `default` clauses.
